import re
from playwright.sync_api import Page


def test_example(page: Page) -> None:
    page.goto("https://www.nu.nl/binnenland/6315272/paginagrote-advertentie-in-kranten-tegen-btw-plannen-van-nieuw-kabinet.html")
    page.goto("https://www2.tst.menzis.nl/")
    page.get_by_role("button", name="Accepteren").click()
    page.get_by_label("Knop gebruikers menu").click()
    page.get_by_role("button", name="Loginstub", exact=True).click()
    page.get_by_placeholder("BSN").click()
    page.get_by_placeholder("BSN").fill("3529811561")
    page.goto("https://www2.tst.menzis.nl/mijn/gegevens/emailadres-controleren?url=/login/inlog-fout")
    page.get_by_label("E-mailadres", exact=True).click()
    page.get_by_label("E-mailadres", exact=True).fill("output.webtesten@menzis.nl")
    page.get_by_label("E-mailadres", exact=True).press("Tab")
    page.get_by_label("Herhaal e-mailadres").fill("output.webtesten@menzis.nl")
    page.goto("https://www2.tst.menzis.nl/")
    page.get_by_label("Knop gebruikers menu").click()
    page.get_by_role("link", name="Mijn berichten").click()
    page.get_by_label("Knop gebruikers menu").click()
    page.goto("https://www2.tst.menzis.nl/mijn/gegevens")
    page.locator("dd").filter(has_text="-55051955Wijzigen").get_by_role("link").click()
    page.get_by_label("Telefoonnummer 1").click()
    page.get_by_label("Telefoonnummer 1").fill("05-55051998")
    page.get_by_role("button", name="Wijzigen").click()
    page.get_by_role("link", name="Terug naar Mijn gegevens").click()
    page.goto("chrome://newtab/")
    page.goto("chrome-error://chromewebdata/")
    page.get_by_role("button", name="Advanced").click()
    page.get_by_role("link", name="Proceed to").click()
    # page.goto("https://intranetapplications.test.otap.loods2.org/TransactionService.Pres.Internal/Default.aspx")
    # page.get_by_role("link", name="Transacties").click()
    # page.frame_locator("iframe[name=\"frContent\"]").get_by_role("link", name="Status").click()
    # page.frame_locator("iframe[name=\"frContent\"]").frame_locator("iframe[name=\"frStatus\"]").get_by_text("wacht op verwerking").click()
    # page.frame_locator("iframe[name=\"frContent\"]").frame_locator("iframe[name=\"frStatus\"]").locator("#ddlTransactieType_dropDownList").select_option("24")
    # page.frame_locator("iframe[name=\"frContent\"]").frame_locator("iframe[name=\"frStatus\"]").get_by_role("button", name="ZOEKEN").click()
